apiVersion: k3d.io/v1alpha2
kind: Simple
name: bee
kubeAPI:
  host: "k3d-bee.localhost"
image: rancher/k3s:v1.21.14-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
labels:
  - label: node-group=local
    nodeFilters:
      - server[0]
registries:
  create: true
  use:
    - k3d-registry.localhost
  config: |
    mirrors:
        docker.io:
            endpoint:
            - http://k3d-k3s-bee-registry:5000
        k3d-registry.localhost:5000:
            endpoint:
            - http://k3d-registry.localhost:5000
options:
  k3d:
    wait: true
    timeout: "60s"
