apiVersion: k3d.io/v1alpha4
kind: Simple
metadata:
  name: bee
kubeAPI:
  host: "127.0.0.1"
image: rancher/k3s:v1.20.15-k3s1
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
registries:
  create:
    proxy:
      remoteURL: https://docker.io 
  use:
    - k3d-registry.localhost
  config: |
    mirrors:
        docker.io:
            endpoint:
            - http://k3d-k3s-bee-registry:5000
        k3d-registry.localhost:5000:
            endpoint:
            - http://k3d-registry.localhost:5000
options:
  k3d:
    wait: true
    timeout: "60s"
  k3s:
    nodeLabels:
      - label: node-group=local
        nodeFilters:
          - server:0
